# Generated by Django 3.0.8 on 2020-07-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IgnitionRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_players', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
            ],
        ),
    ]
