# Generated by Django 3.0.8 on 2020-07-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ignitionrow',
            name='num_players',
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='num_players_200',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='num_players_25',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='num_players_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='num_players_50',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='num_players_500',
            field=models.IntegerField(default=0),
        ),
    ]
