# Generated by Django 3.0.8 on 2020-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignition', '0002_auto_20200726_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignitionrow',
            name='avg_pot_200',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='avg_pot_25',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='avg_pot_5',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='avg_pot_50',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='avg_pot_500',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ignitionrow',
            name='num_players_200',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ignitionrow',
            name='num_players_25',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ignitionrow',
            name='num_players_5',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ignitionrow',
            name='num_players_50',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ignitionrow',
            name='num_players_500',
            field=models.IntegerField(default=-1),
        ),
    ]
