# Generated by Django 3.0.8 on 2020-07-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignition', '0003_auto_20200726_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignitionrow',
            name='pct_flop_200',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='pct_flop_25',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='pct_flop_5',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='pct_flop_50',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ignitionrow',
            name='pct_flop_500',
            field=models.IntegerField(default=-1),
        ),
    ]
