# Generated by Django 3.1 on 2020-10-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ignition', '0005_mymodel_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnitionRowPredictionCVX',
            fields=[
                ('ignitionrow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ignition.ignitionrow')),
            ],
            bases=('ignition.ignitionrow',),
        ),
        migrations.CreateModel(
            name='IgnitionRowPredictionOLS',
            fields=[
                ('ignitionrow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ignition.ignitionrow')),
            ],
            bases=('ignition.ignitionrow',),
        ),
    ]
